[package]
name = "pawkit-holy-array"
version = "0.1.4"
edition = "2024"
license = "MPL-2.0"
homepage = "https://teamvulpine.com"
repository = "https://github.com/TeamVulpine/PawKit/tree/main/holy-array"
description = "A small library implemnenting a freelist"

[dependencies]
