[package]
name = "pawkit-godot"
version = "0.1.9"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pawkit-logger.workspace = true
pawkit-net.workspace = true
pawkit-net-signaling.workspace = true

serde.workspace = true
tokio.workspace = true

godot.workspace = true
